plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'kotlin-parcelize'
    id 'kotlin-kapt'
    id 'com.google.devtools.ksp'
    id 'androidx.room'
}

android {

    signingConfigs {
        release {
            storeFile file('/home/chaolee/AndroidStudioProjects/keystore/new_key.jks')
            storePassword '86637971'
            keyAlias = 'chaolee1959'
            keyPassword '86637971'
        }
    }

    compileSdk = sdk_version.compile

    defaultConfig {

        targetSdk sdk_version.target
        minSdk sdk_version.min

        versionCode 1019
        versionName "10.19"

        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        signingConfig signingConfigs.release
    }

    flavorDimensions += ["karaoke"]
    productFlavors {
        register("karaokeplayer") {
            dimension = "karaoke"
            applicationId = "com.smile.karaokeplayer"
        }
        register("karaokeplayer2") {
            // for Amazon app store only
            // has same package name with "karaokeplayer"
            dimension = "karaoke"
            applicationId = "com.smile.karaokeplayer"
        }
        register("videoplayer") {
            dimension = "karaoke"
            applicationId = "com.smile.videoplayer"
        }
        register("videoplayer2") {
            // for Amazon app store only
            // has same package name with "videoplayer"
            dimension = "karaoke"
            applicationId = "com.smile.videoplayer"
        }
        register("karaoketvplayer") {
            dimension = "karaoke"
            applicationId = "com.smile.karaoketvplayer"
            isDefault = true
        }
        register("u2bplayer") {
            dimension = "karaoke"
            versionCode 126
            versionName "1.26"
            applicationId = "com.smile.u2bplayer"
        }
        register("u2bplayer2") {
            // for Amazon app store only
            dimension = "karaoke"
            versionCode 126
            versionName "1.26"
            applicationId = "com.smile.youtubeplayer"
        }
        register("u2bkaraoke") {
            dimension = "karaoke"
            versionCode 115
            versionName "1.15"
            applicationId = "com.smile.u2bkaraoke"
        }
        register("u2bkktool") {
            dimension = "karaoke"
            versionCode 103
            versionName "1.03"
            applicationId = "com.smile.u2bkktool"
        }
        register("u2bkktool2") {
            dimension = "karaoke"
            versionCode 103
            versionName "1.03"
            applicationId = "com.smile.u2bkktool2"
        }
    }

    // println("projectDir = ${project.projectDir}")

    sourceSets {
        main {
            java.srcDir("src/main/java")
            resources.srcDir("src/main/rec")
            manifest {
                srcFile "src/main/AndroidManifest.xml"
            }
        }

        karaokeplayer {
            java.srcDirs += ["src/karaokeplayer/java"]
            res.srcDirs += ["src/karaokeplayer/res"]
            manifest {
                srcFile "src/karaokeplayer/AndroidManifest.xml"
            }
        }

        karaokeplayer2 {
            java.srcDirs += ["src/karaokeplayer2/java", "src/karaokeplayer/java"]
            res.srcDirs += ["src/karaokeplayer/res"]
            manifest {
                srcFile "src/karaokeplayer2/AndroidManifest.xml"
            }
        }

        videoplayer {
            java.srcDirs += ["src/videoplayer/java"]
            res.srcDirs += ["src/videoplayer/res"]
            manifest {
                srcFile "src/videoplayer/AndroidManifest.xml"
            }
        }

        videoplayer2 {
            java.srcDirs += ["src/videoplayer2/java", "src/videoplayer/java"]
            res.srcDirs += ["src/videoplayer/res"]
            manifest {
                srcFile "src/videoplayer2/AndroidManifest.xml"
            }
        }

        karaoketvplayer {
            java.srcDirs += ["src/karaoketvplayer/java", "src/karaokeplayer/java",
                             "src/videoplayer/java", "src/u2bplayer/java",
                             "src/u2bkaraoke/java"]
            res.srcDirs += ["src/karaoketvplayer/res", "src/karaokeplayer/res",
                            "src/videoplayer/res", "src/u2bplayer/res",
                            "src/u2bkaraoke/res"]
            manifest {
                srcFile "src/karaoketvplayer/AndroidManifest.xml"
            }
        }

        u2bplayer {
            java.srcDirs += ["src/u2bplayer/java"]
            res.srcDirs += ["src/u2bplayer/res"]
            manifest {
                srcFile "src/u2bplayer/AndroidManifest.xml"
            }
        }

        u2bplayer2 {
            // for Amazon app store only
            java.srcDirs += ["src/u2bplayer2/java", "src/u2bplayer/java"]
            res.srcDirs += ["src/u2bplayer/res"]
            manifest {
                srcFile "src/u2bplayer2/AndroidManifest.xml"
            }
        }

        u2bkaraoke {
            java.srcDirs += ["src/u2bkaraoke/java", "src/u2bplayer/java"]
            res.srcDirs += ["src/u2bkaraoke/res", "src/u2bplayer/res"]
            manifest {
                srcFile "src/u2bkaraoke/AndroidManifest.xml"
            }
        }

        u2bkktool {
            java.srcDirs += ["src/u2bkktool/java", "src/u2bkaraoke/java",
                             "src/u2bplayer/java"]
            res.srcDirs += ["src/u2bkktool/res", "src/u2bkaraoke/res",
                            "src/u2bplayer/res"]
            manifest {
                srcFile "src/u2bkktool/AndroidManifest.xml"
            }
        }
        u2bkktool2 {
            java.srcDirs += ["src/u2bkktool/java", "src/u2bkaraoke/java",
                             "src/u2bplayer/java"]
            res.srcDirs += ["src/u2bkktool2/res", "src/u2bkaraoke/res",
                            "src/u2bplayer/res"]
            manifest {
                srcFile "src/u2bkktool/AndroidManifest.xml"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
            // shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    /*
    kotlinOptions {
        jvmTarget = '17'    // deprecated
        // for default fun of Kotlin
        freeCompilerArgs = ['-Xjvm-default=all']    // deprecated
    }
    */

    composeOptions {
        kotlinCompilerExtensionVersion '1.5.15'
    }

    buildFeatures  {
        viewBinding true
        dataBinding true
        buildConfig true
        compose true
    }

    room {
        schemaDirectory "$projectDir/schemas"
    }

    namespace 'com.smile.karaoke'
    // testNamespace 'com.smile.karaoke.androidTest'
}

allprojects {
    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.media:media:1.8.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    // implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation "androidx.annotation:annotation:1.10.0"
    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation 'com.google.firebase:firebase-ads:23.6.0'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'com.google.android.ump:user-messaging-platform:4.0.0'

    implementation 'com.facebook.android:audience-network-sdk:6.22.0'
    implementation 'com.facebook.infer.annotation:infer-annotation:0.18.0'

    // Compose BOM (Bill of Materials) - Recommended for managing versions
    // Use the latest BOM version
    implementation platform('androidx.compose:compose-bom:2026.09.00')
    // Compose Runtime
    implementation 'androidx.compose.runtime:runtime'
    // Other Compose dependencies you might be using (UI, Material, etc.)
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.material3:material3' // Or material
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.activity:activity-ktx:1.13.0'
    implementation('androidx.fragment:fragment-ktx:1.9.0')
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.11.0'
    implementation 'androidx.activity:activity-compose:1.13.0'
    implementation 'androidx.compose.ui:ui-graphics'
    implementation 'androidx.mediarouter:mediarouter:1.8.1'
    implementation 'androidx.media3:media3-cast:1.11.1'  // for exoplayer and vlcplayer
    // implementation 'androidx.media3:media3-exoplayer:1.11.1'
    // implementation 'com.google.android.gms:play-services-cast-framework:22.1.0'
    // implementation "com.pierfrancescosoffritti.androidyoutubeplayer:core:13.0.0"

    implementation 'com.android.billingclient:billing-ktx:9.1.0'

    implementation 'androidx.tracing:tracing-perfetto-handshake:1.0.1'
    implementation 'org.nanohttpd:nanohttpd:2.3.1'

    implementation files('libs/smilelibraries-release.aar')
    implementation files('libs/NativeTemplatesModels-release.aar')

    // ... other dependencies
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:5.5.0'
    // For coroutines (optional, but recommended for modern Android development)
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0'
    implementation 'com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2'

    implementation 'io.coil-kt:coil:2.7.0'

    implementation 'androidx.room:room-ktx:2.8.5'
    ksp 'androidx.room:room-compiler:2.8.5'
    implementation 'androidx.room:room-runtime:2.8.5'

    implementation 'com.google.dagger:dagger:2.60.1'
    ksp 'com.google.dagger:dagger-android-processor:2.60.1'
    ksp 'com.google.dagger:dagger-compiler:2.60.1'

    // This block runs after the project is configured
    afterEvaluate {
        android.applicationVariants.all { variant ->
            variant.productFlavors.each { flavor ->
                // println("variant.name = ${variant.name}")
                if (flavor.name.containsIgnoreCase("karaoke")) {
                    // Dynamically add a dependency to this variant
                    dependencies.add(variant.name + "Implementation", "androidx.media3:media3-exoplayer:1.11.1")
                    dependencies.add(variant.name + "Implementation", "androidx.media3:media3-exoplayer-dash:1.11.1")
                    dependencies.add(variant.name + "Implementation", "androidx.media3:media3-decoder:1.11.1")
                    dependencies.add(variant.name + "Implementation", "androidx.media3:media3-ui:1.11.1")
                    dependencies.add(variant.name + "Implementation", "androidx.media3:media3-session:1.11.1")
                    dependencies.add(variant.name + "Implementation", project(":extension-ffmpeg"))
                    dependencies.add(variant.name + "Implementation", project(":extension-flac"))
                    dependencies.add(variant.name + "Implementation", project(":extension-opus"))
                    dependencies.add(variant.name + "Implementation", project(":extension-av1"))
                    // dependencies.add(variant.name + "Implementation", project(":extension-vp9"))
                    // Note: You use the full variant name (e.g., "karaokeplayerDebugImplementation")
                }
                if (flavor.name.containsIgnoreCase("karaoketvplayer")
                        || flavor.name.containsIgnoreCase("u2bplayer")
                        || flavor.name.containsIgnoreCase("u2bkaraoke")
                        || flavor.name.containsIgnoreCase("u2bkktool")) {
                    // Check for latest version
                    dependencies.add(variant.name + "Implementation",
                            "com.pierfrancescosoffritti.androidyoutubeplayer:core:13.0.0")
                    dependencies.add(variant.name + "Implementation",
                            "com.pierfrancescosoffritti.androidyoutubeplayer:custom-ui:13.0.0")
                    dependencies.add(variant.name + "Implementation",
                        "com.pierfrancescosoffritti.androidyoutubeplayer:chromecast-sender:0.32")
                }
                if (flavor.name.containsIgnoreCase("videoplayer")   // includes videoplayer2
                        || flavor.name.containsIgnoreCase("karaoketvplayer")
                        || flavor.name.containsIgnoreCase("karaokeplayer2")) {
                    dependencies.add(variant.name + "Implementation", "org.videolan.android:libvlc-all:3.6.5")
                    // Note: You use the full variant name (e.g., "videoDebugImplementation")
                }
            }
        }
    }

    debugImplementation 'androidx.compose.ui:ui-tooling'
    debugImplementation 'androidx.compose.ui:ui-test-manifest:1.12.1'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'androidx.room:room-testing:2.8.5'
    androidTestImplementation platform('androidx.compose:compose-bom:2026.09.00')
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test:rules:1.7.0'
    androidTestImplementation 'androidx.test.ext:truth:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.4.0'
}

apply plugin: 'com.google.gms.google-services'
