
apply plugin: 'com.android.library'

android {
    compileSdk = sdk_version.compile

    defaultConfig {
        targetSdk sdk_version.target
        minSdk sdk_version.min
        consumerProguardFiles 'proguard-rules.txt'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    sourceSets.main {
        jniLibs.srcDir 'src/main/libs'
        jni.srcDirs = [] // Disable the automatic ndk-build call by Android Studio.
    }

    namespace 'androidx.media3.decoder.vp9'
}

dependencies {
    implementation "androidx.annotation:annotation:1.10.0"
    implementation 'androidx.media3:media3-common:1.11.1'
    implementation 'androidx.media3:media3-exoplayer:1.11.1'
    implementation 'androidx.media3:media3-decoder:1.11.1'
    compileOnly 'org.checkerframework:checker-qual:4.2.3'
    compileOnly 'org.jetbrains.kotlin:kotlin-annotations-jvm:2.2.21'
}
