
apply plugin: 'com.android.library'

android {
    compileSdk = sdk_version.compile

    defaultConfig {
        targetSdk sdk_version.target
        minSdk sdk_version.min
        consumerProguardFiles 'proguard-rules.txt'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

        externalNativeBuild {
            cmake {
                arguments "-DWITH_OGG=OFF"
                arguments "-DINSTALL_MANPAGES=OFF"
                targets "flacJNI"
            }
        }
        ndk {
            abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
        }
    }

    ndkVersion '27.3.13750724'
    externalNativeBuild {
        cmake {
            path file('../flac/src/main/jni/CMakeLists.txt')
            version '3.21.0+'
        }
    }

    namespace 'androidx.media3.decoder.flac'
}

dependencies {
    implementation "androidx.annotation:annotation:1.10.0"
    implementation 'androidx.media3:media3-common:1.11.1'
    implementation 'androidx.media3:media3-exoplayer:1.11.1'
    implementation 'androidx.media3:media3-decoder:1.11.1'
    compileOnly 'org.checkerframework:checker-qual:4.2.3'
    compileOnly 'org.jetbrains.kotlin:kotlin-annotations-jvm:2.2.21'
}
